
/*Sample insert statement*/

Insert into MAPPING_PK_CONFIG (ID,MICROSERVICENAME,LEGACY_SCHEMA,LEGACY_TABLE,LEGACYCOLUMN,AZURE_DB,AZURE_SCHEMA,AZURE_TABLE,AZURECOLUMN,COMMENTS,PK_COLUMN,PK_OPERATOR,PK_CRITERIA,PK_POSITION,AZURE_DATA_TYPE,DIFF_REQ) 
values (1,'APP_NAME','SOURCE','TABLE_TEST','COLUMN_TEST','DBName','TARGET','TABLE_TEST','COLUMN_TEST',null,'Y','=',null,null,'VARCHAR2','Y');
COMMIT;